Add RegistrantChange specification to OpenAPI definition
dnsimple/dnsimple-developer pull request #501
Opened 2023-07-17 22:40 UTC by juankuquintana

https://github.com/dnsimple/dnsimple-business/issues/1709

We add the definition to the OpenAPI specification of:

```
  get     "/:account_id/registrant_changes"
  post   "/:account_id/registrant_changes"
  post   "/:account_id/registrant_changes/check"
  get     "/:account_id/registrant_changes/:registrant_change_id"
  delete  "/:account_id/registrant_changes/:registrant_change_id"
```
### Delete
```curl
curl -i  -H 'Authorization: Bearer **********' \
      -H 'Accept: application/json' \
      -H 'Content-Type: application/json' \
      -X DELETE \
      http://api.localhost:5000/v2/2/registrant_changes/:id
```

### Index
```curl
curl -i  -H 'Authorization: Bearer **********' \
      -H 'Accept: application/json' \
      -X GET \
      http://api.localhost:5000/v2/2/registrant_changes
```

### Show
```curl
curl -i  -H 'Authorization: Bearer **********' \
      -H 'Accept: application/json' \
      -X GET \
      http://api.localhost:5000/v2/2/registrant_changes/:registrant_id
```

### Check
```curl
curl -i  -H 'Authorization: Bearer **********' \
      -H 'Accept: application/json' \
      -H 'Content-Type: application/json' \
      -X POST \
      -d '{ "domain_id":"**********", "contact_id": ********** }' \
      http://api.localhost:5000/v2/2/registrant_changes/check
```

### Create
```curl
curl -i  -H 'Authorization: Bearer **********' \
      -H 'Accept: application/json' \
      -H 'Content-Type: application/json' \
      -X POST \
      -d '{ "domain_id":"**********", "contact_id": **********, "extended_attributes": {} }' \
      http://api.localhost:5000/v2/2/registrant_changes
```

## :mag: QA

## :shipit: Pre/Post tasks

## :shipit: Verification

- [ ] SHA is deployed

2023-07-17 22:58 UTC, juankuquintana commented on content/v2/openapi.yml
> +      description: List contact changes in the account.
We are using two languages, contact changes to the "end user" and registrant change as domain scope. I'm unsure if it's confusing and would appreciate suggestions.

2023-07-18 06:41 UTC, DXTimer commented on content/v2/openapi.yml
> +      summary: Check a contact change
Maybe:

```suggestion
      summary: Check a contact change requirements
```

2023-07-18 06:52 UTC, DXTimer commented on content/v2/openapi.yml
> +    ExtendedAttributes:
What do you think about changing the name of this schema to `ContactExtendedAttributes`? Since we already have extended attributes for the TLDs.

2023-07-18 06:59 UTC, DXTimer commented on content/v2/openapi.yml
> +                type: string
We likely do not limit the input to be strictly a string so we could update this to:
```suggestion
                type:
                  - string
                  - integer
```

2023-07-18 07:00 UTC, DXTimer approved these changes
Left some suggestions and comments, otherwise, the changes look good.

2023-07-18 07:18 UTC, kntsoriano requested changes

2023-07-18 07:18 UTC, kntsoriano commented on content/v2/openapi.yml
> +          description: Successfully changed the contact.
I think this is the wrong description.

2023-07-18 15:48 UTC, merged